import Foundation

struct AulasMock {
    static let lista: [Aula] = [
        Aula(materia: "Língua Portuguesa", numero: 1, tema: "Ortografia oficial", data: Calendar.current.date(byAdding: .day, value: 8, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 2, tema: "Classes de palavras: substantivos, adjetivos, artigos, numerais, advérbios, pronomes e interjeições. Colocação dos pronomes átonos", data: Calendar.current.date(byAdding: .day, value: 8, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 3, tema: "Classes de palavras: conjunções", data: Calendar.current.date(byAdding: .day, value: 8, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 4, tema: "Classes de palavras: verbos. Tempos e modos verbais. Correlação e vozes verbais", data: Calendar.current.date(byAdding: .day, value: 8, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 5, tema: "Estrutura morfossintática do período. Coordenação e subordinação", data: Calendar.current.date(byAdding: .day, value: 8, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 6, tema: "Emprego dos sinais de pontuação", data: Calendar.current.date(byAdding: .day, value: 9, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 7, tema: "Concordância verbal e nominal", data: Calendar.current.date(byAdding: .day, value: 9, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 8, tema: "Regência verbal e crase", data: Calendar.current.date(byAdding: .day, value: 9, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 9, tema: "Coesão textual, reescrita, significação", data: Calendar.current.date(byAdding: .day, value: 9, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 10, tema: "Compreensão e interpretação de textos", data: Calendar.current.date(byAdding: .day, value: 9, to: Date())!),
        Aula(materia: "Língua Portuguesa", numero: 11, tema: "Correspondência oficial", data: Calendar.current.date(byAdding: .day, value: 10, to: Date())!),
        Aula(materia: "Atualidades", numero: 1, tema: "Economia Internacional", data: Calendar.current.date(byAdding: .day, value: 10, to: Date())!),
        Aula(materia: "Atualidades", numero: 2, tema: "Política e Sociedade Internacional I", data: Calendar.current.date(byAdding: .day, value: 10, to: Date())!),
        Aula(materia: "Atualidades", numero: 3, tema: "Política e Sociedade Internacional II", data: Calendar.current.date(byAdding: .day, value: 10, to: Date())!),
        Aula(materia: "Atualidades", numero: 4, tema: "Economia Brasileira", data: Calendar.current.date(byAdding: .day, value: 10, to: Date())!),
        Aula(materia: "Atualidades", numero: 5, tema: "Política e Sociedade Brasileira I", data: Calendar.current.date(byAdding: .day, value: 11, to: Date())!),
        Aula(materia: "Atualidades", numero: 6, tema: "Política e Sociedade Brasileira II", data: Calendar.current.date(byAdding: .day, value: 11, to: Date())!),
        Aula(materia: "Atualidades", numero: 7, tema: "Ecologia e Desenvolvimento Sustentável", data: Calendar.current.date(byAdding: .day, value: 12, to: Date())!),
        Aula(materia: "Atualidades", numero: 8, tema: "Retrospectivas Mensais de Atualidades", data: Calendar.current.date(byAdding: .day, value: 12, to: Date())!),
        Aula(materia: "Arquivologia", numero: 1, tema: "Introdução à Arquivologia e princípios", data: Calendar.current.date(byAdding: .day, value: 13, to: Date())!),
        Aula(materia: "Arquivologia", numero: 2, tema: "Classificação de documentos", data: Calendar.current.date(byAdding: .day, value: 13, to: Date())!),
        Aula(materia: "Arquivologia", numero: 3, tema: "Ciclo Vital dos documentos", data: Calendar.current.date(byAdding: .day, value: 14, to: Date())!),
        Aula(materia: "Arquivologia", numero: 4, tema: "Métodos de Arquivamento", data: Calendar.current.date(byAdding: .day, value: 14, to: Date())!),
        Aula(materia: "Arquivologia", numero: 5, tema: "Arquivos Correntes e Protocolo", data: Calendar.current.date(byAdding: .day, value: 15, to: Date())!),
        Aula(materia: "Arquivologia", numero: 6, tema: "Arquivo Intermediário", data: Calendar.current.date(byAdding: .day, value: 15, to: Date())!),
        Aula(materia: "Arquivologia", numero: 7, tema: "Arquivos Permanentes", data: Calendar.current.date(byAdding: .day, value: 15, to: Date())!),
        Aula(materia: "Arquivologia", numero: 8, tema: "Preservação e conservação de documentos", data: Calendar.current.date(byAdding: .day, value: 15, to: Date())!),
        Aula(materia: "Arquivologia", numero: 9, tema: "Gestão Eletrônica de Documentos", data: Calendar.current.date(byAdding: .day, value: 15, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 1, tema: "Estruturas Lógicas", data: Calendar.current.date(byAdding: .day, value: 15, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 2, tema: "Equivalências Lógicas", data: Calendar.current.date(byAdding: .day, value: 46, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 3, tema: "Diagramas Lógicos", data: Calendar.current.date(byAdding: .day, value: 46, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 4, tema: "Lógica de Primeira Ordem", data: Calendar.current.date(byAdding: .day, value: 46, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 5, tema: "Lógica de Argumentação", data: Calendar.current.date(byAdding: .day, value: 46, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 6, tema: "Associações Lógicas", data: Calendar.current.date(byAdding: .day, value: 46, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 7, tema: "Teoria dos Conjuntos", data: Calendar.current.date(byAdding: .day, value: 76, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 8, tema: "Conjuntos Numéricos", data: Calendar.current.date(byAdding: .day, value: 76, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 9, tema: "Operações, Potenciação e Radiciação", data: Calendar.current.date(byAdding: .day, value: 76, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 10, tema: "MMC e MDC", data: Calendar.current.date(byAdding: .day, value: 76, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 11, tema: "Frações, Razões e Proporções", data: Calendar.current.date(byAdding: .day, value: 76, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 12, tema: "Regra de Três", data: Calendar.current.date(byAdding: .day, value: 107, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 13, tema: "Porcentagem", data: Calendar.current.date(byAdding: .day, value: 107, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 14, tema: "Equações 1º Grau", data: Calendar.current.date(byAdding: .day, value: 107, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 15, tema: "Geometria Plana e Espacial", data: Calendar.current.date(byAdding: .day, value: 107, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 16, tema: "Matrizes e Determinantes", data: Calendar.current.date(byAdding: .day, value: 107, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 17, tema: "Sistemas Lineares", data: Calendar.current.date(byAdding: .day, value: 138, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 18, tema: "Análise Combinatória", data: Calendar.current.date(byAdding: .day, value: 138, to: Date())!),
        Aula(materia: "Raciocínio Lógico e Matemática", numero: 19, tema: "Probabilidade", data: Calendar.current.date(byAdding: .day, value: 138, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 1, tema: "Conceitos de Internet e Intranet", data: Calendar.current.date(byAdding: .day, value: 138, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 2, tema: "Navegadores e Correio Eletrônico", data: Calendar.current.date(byAdding: .day, value: 138, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 3, tema: "Sites de busca, redes sociais e cloud", data: Calendar.current.date(byAdding: .day, value: 229, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 4, tema: "Segurança da informação", data: Calendar.current.date(byAdding: .day, value: 229, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 5, tema: "Procedimentos de backup", data: Calendar.current.date(byAdding: .day, value: 229, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 6, tema: "RAID", data: Calendar.current.date(byAdding: .day, value: 229, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 7, tema: "Excel", data: Calendar.current.date(byAdding: .day, value: 229, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 8, tema: "Calc", data: Calendar.current.date(byAdding: .day, value: 23, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 9, tema: "Word", data: Calendar.current.date(byAdding: .day, value: 23, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 10, tema: "Writer", data: Calendar.current.date(byAdding: .day, value: 23, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 11, tema: "PowerPoint", data: Calendar.current.date(byAdding: .day, value: 23, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 12, tema: "Impress", data: Calendar.current.date(byAdding: .day, value: 23, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 13, tema: "Windows", data: Calendar.current.date(byAdding: .day, value: 24, to: Date())!),
        Aula(materia: "Noções de Informática", numero: 14, tema: "Linux", data: Calendar.current.date(byAdding: .day, value: 24, to: Date())!),
        Aula(materia: "Administração de Recursos Materiais", numero: 1, tema: "Conceitos e Ética", data: Calendar.current.date(byAdding: .day, value: 24, to: Date())!),
        Aula(materia: "Administração de Recursos Materiais", numero: 2, tema: "Classificação de Materiais", data: Calendar.current.date(byAdding: .day, value: 24, to: Date())!),
        Aula(materia: "Administração de Recursos Materiais", numero: 3, tema: "Compras e Lote Econômico", data: Calendar.current.date(byAdding: .day, value: 24, to: Date())!),
        Aula(materia: "Administração de Recursos Materiais", numero: 4, tema: "Estoques I", data: Calendar.current.date(byAdding: .day, value: 25, to: Date())!),
        Aula(materia: "Administração de Recursos Materiais", numero: 5, tema: "Estoques II", data: Calendar.current.date(byAdding: .day, value: 25, to: Date())!),
        Aula(materia: "Administração de Recursos Materiais", numero: 6, tema: "Armazenagem", data: Calendar.current.date(byAdding: .day, value: 25, to: Date())!),
        Aula(materia: "Administração de Recursos Materiais", numero: 7, tema: "Gestão Patrimonial", data: Calendar.current.date(byAdding: .day, value: 25, to: Date())!),
        Aula(materia: "Noções de Gestão de Pessoas", numero: 1, tema: "Conceitos e Funções", data: Calendar.current.date(byAdding: .day, value: 25, to: Date())!),
        Aula(materia: "Noções de Gestão de Pessoas", numero: 2, tema: "Desempenho", data: Calendar.current.date(byAdding: .day, value: 26, to: Date())!),
        Aula(materia: "Noções de Gestão de Pessoas", numero: 3, tema: "Liderança", data: Calendar.current.date(byAdding: .day, value: 26, to: Date())!),
        Aula(materia: "Noções de Gestão de Pessoas", numero: 4, tema: "Comportamento organizacional", data: Calendar.current.date(byAdding: .day, value: 26, to: Date())!),
        Aula(materia: "Noções de Gestão de Pessoas", numero: 5, tema: "Clima Organizacional", data: Calendar.current.date(byAdding: .day, value: 26, to: Date())!),
        Aula(materia: "Noções de Administração Pública", numero: 1, tema: "Organizações formais", data: Calendar.current.date(byAdding: .day, value: 26, to: Date())!),
        Aula(materia: "Noções de Administração Pública", numero: 2, tema: "Gestão de processos", data: Calendar.current.date(byAdding: .day, value: 29, to: Date())!),
        Aula(materia: "Noções de Administração Pública", numero: 3, tema: "Organização administrativa da União", data: Calendar.current.date(byAdding: .day, value: 29, to: Date())!),
        Aula(materia: "Noções de Administração Pública", numero: 4, tema: "Gestão de contratos", data: Calendar.current.date(byAdding: .day, value: 29, to: Date())!),
        Aula(materia: "Legislação Aplicada à PF", numero: 1, tema: "Estatuto do Desarmamento", data: Calendar.current.date(byAdding: .day, value: 29, to: Date())!),
        Aula(materia: "Legislação Aplicada à PF", numero: 2, tema: "Estatuto da Segurança Privada", data: Calendar.current.date(byAdding: .day, value: 29, to: Date())!),
        Aula(materia: "Legislação Aplicada à PF", numero: 3, tema: "Lei de produtos químicos", data: Calendar.current.date(byAdding: .day, value: 30, to: Date())!),
        Aula(materia: "Legislação Aplicada à PF", numero: 4, tema: "Investigação criminal (delegado)", data: Calendar.current.date(byAdding: .day, value: 30, to: Date())!),
        Aula(materia: "Legislação Aplicada à PF", numero: 5, tema: "Lei de Migração", data: Calendar.current.date(byAdding: .day, value: 30, to: Date())!),
        Aula(materia: "Noções de Administração Financeira e Orçamentária", numero: 1, tema: "Orçamento público e planos", data: Calendar.current.date(byAdding: .day, value: 30, to: Date())!),
        Aula(materia: "Noções de Administração Financeira e Orçamentária", numero: 2, tema: "Princípios orçamentários", data: Calendar.current.date(byAdding: .day, value: 30, to: Date())!),
        Aula(materia: "Noções de Administração Financeira e Orçamentária", numero: 3, tema: "Créditos e ciclo orçamentário", data: Calendar.current.date(byAdding: .day, value: 31, to: Date())!),
        Aula(materia: "Noções de Administração Financeira e Orçamentária", numero: 4, tema: "Receita pública e dívida ativa", data: Calendar.current.date(byAdding: .day, value: 31, to: Date())!),
        Aula(materia: "Noções de Administração Financeira e Orçamentária", numero: 5, tema: "Despesa pública e classificações", data: Calendar.current.date(byAdding: .day, value: 31, to: Date())!),
        Aula(materia: "Noções de Administração Financeira e Orçamentária", numero: 6, tema: "Execução orçamentária", data: Calendar.current.date(byAdding: .day, value: 31, to: Date())!),
        Aula(materia: "Noções de Administração Financeira e Orçamentária", numero: 7, tema: "Lei de Responsabilidade Fiscal", data: Calendar.current.date(byAdding: .day, value: 31, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 1, tema: "Administração Pública", data: Calendar.current.date(byAdding: .day, value: 32, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 2, tema: "Organização administrativa", data: Calendar.current.date(byAdding: .day, value: 32, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 3, tema: "Poderes e Atos Administrativos", data: Calendar.current.date(byAdding: .day, value: 32, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 4, tema: "Licitações (Lei 14.133)", data: Calendar.current.date(byAdding: .day, value: 32, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 5, tema: "Controle, Responsabilidade Civil", data: Calendar.current.date(byAdding: .day, value: 32, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 6, tema: "Agentes Públicos", data: Calendar.current.date(byAdding: .day, value: 33, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 7, tema: "Lei 8.112", data: Calendar.current.date(byAdding: .day, value: 33, to: Date())!),
        Aula(materia: "Noções de Direito Administrativo", numero: 8, tema: "Decreto nº 1.171", data: Calendar.current.date(byAdding: .day, value: 33, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 1, tema: "Direitos Fundamentais", data: Calendar.current.date(byAdding: .day, value: 33, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 2, tema: "Direitos individuais e coletivos", data: Calendar.current.date(byAdding: .day, value: 33, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 3, tema: "Direitos sociais", data: Calendar.current.date(byAdding: .day, value: 36, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 4, tema: "Nacionalidade e Cidadania", data: Calendar.current.date(byAdding: .day, value: 36, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 5, tema: "Partidos políticos", data: Calendar.current.date(byAdding: .day, value: 36, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 6, tema: "Organização do Estado", data: Calendar.current.date(byAdding: .day, value: 36, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 7, tema: "Administração pública", data: Calendar.current.date(byAdding: .day, value: 36, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 8, tema: "Poder executivo", data: Calendar.current.date(byAdding: .day, value: 37, to: Date())!),
        Aula(materia: "Noções de Direito Constitucional", numero: 9, tema: "Segurança Pública", data: Calendar.current.date(byAdding: .day, value: 37, to: Date())!),
    ]
}
